---
- hosts: baremetal
  name: "Create configuration drive files and deploy machines from inventory"
  become: no
  gather_facts: no
  roles:
    - role: bifrost-configdrives-dynamic		
      delegate_to: "{{ groups['target'][0] }}"
    - role: bifrost-deploy-nodes-dynamic
      delegate_to: "{{ groups['target'][0] }}"
